/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vvtdlqdzmtonhmsylurq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dGRscWR6bXRvbmhtc3lsdXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODEwNjMsImV4cCI6MjA4NjM1NzA2M30.YP_kmwx56OKJYbiEJJ2SJszzFVAF92-0XxUy-rHxtDo"